### ISSUE TITLE
Fail to load model

### ISSUE THREAD

**Issue by okideal** [Aimol-l/OrtInference#14]
大佬好，我在linux下加载img_decoder的时候遇见Failed to load model. Please check your onnx file!
四个onnx模型都是直接通过SAM2-export 项目导出的

**Comment by Aimol-l** [comment]
没有任何信息，没法回答。你用这些模型试试吧。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Aimol-l/OrtInference"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月21日(星期四) 下午5:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Aimol-l/OrtInference] Fail to load model (Issue #14)





 
大佬好，我在linux下加载img_decoder的时候遇见Failed to load model. Please check your onnx file!
 四个onnx模型都是直接通过SAM2-export 项目导出的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

small.zip (169.27M, 2024年12月21日 17:25 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0f366237859252c5a73c8ba642350b1f49420102575608521c54070652185b02550e4f0700500e1d080f505456570f060557010e643c39435c570e5b4a4f5040310b&code=16b7d590

**Comment by okideal** [comment]
我用python加载onnx也会出错
`import onnxruntime as ort

img_decoder_onnx = "checkpoints/small/image_decoder.onnx"
sess = ort.InferenceSession(img_decoder_onnx)
print(sess.get_inputs())`

报错
`line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /home/ivys/SAM2Export/checkpoints/small/image_decoder.onnx failed:Type Error: Type parameter (T) of Optype (Where) bound to different types (tensor(float) and tensor(double) in node (/Where_9).`
